jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix package conflicts & install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -f
          sudo dpkg --configure -a
          sudo apt-get autoremove -y
          sudo apt-get clean
          
          # Install Docker
          sudo apt-get install -y docker.io
          
          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Deploy to Local Docker
        run: |
          docker-compose up -d
      - name: Notify Slack
        run: |
             curl -X POST -H 'Content-type: application/json' --data '{"text": "Test webhook notification from CI/CD"}' https://hooks.slack.com/services/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
